# -*- coding: utf-8 -*-
"""Webscrapping covid 19 stats

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1sojlz05NwcCYtWf6l5Bf9M2ZnYn26qII
"""

from bs4 import BeautifulSoup
import requests
import openpyxl

excel = openpyxl.Workbook()
sheet = excel.active

sheet.title = "COVID 19 DATA"
sheet.append(["COUNTRY","CASES","DEATH","CONTINENT"])

try:
    page = requests.get('https://www.worldometers.info/coronavirus/countries-where-coronavirus-has-spread/')
    soup = BeautifulSoup(page.text,"html.parser")
    data_iterator = iter(soup.find_all('td'))
    while True:
      try:
        country = next(data_iterator).text
        confirmed = next(data_iterator).text
        deaths = next(data_iterator).text
        continent = next(data_iterator).text
        print(country,confirmed,deaths,continent)
        sheet.append([country,confirmed,deaths,continent]) 
      except StopIteration:
        break
      excel.save('COVID 19 DATA.xlsx')
except Exception as e:
    print(e)